---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(finalfit)
library(mice)
library(purrr)
library(dplyr)
```

# Load Data
```{r}
heart.radiomics = read.csv("data/heart.radiomics.csv")
heart.traditional = read.csv("data/cardio.data.csv")
heart.bai = read.csv('data/heart.measures.bai.csv')
```

# Prep Radiomics Data
```{r}
heart.radiomics.notdeprecated = heart.radiomics[,heart.radiomics[1,]!="Deprecated"]
```

```{r}
feature.groups = read.csv("data/radiomics.groups.csv")
```

```{r}
new_cols = paste(feature.groups[,2],
             colnames(heart.radiomics.notdeprecated)[2:ncol(heart.radiomics.notdeprecated)],
             sep = "_")
colnames(heart.radiomics.notdeprecated)[2:ncol(heart.radiomics.notdeprecated)] = new_cols
```

```{r}
feature.groups$Feature = colnames(heart.radiomics.notdeprecated)[2:ncol(heart.radiomics.notdeprecated)]
heart.groups = feature.groups[grep("MYO|shape",feature.groups$Feature),2]
```


```{r}
heart.radiomics.touse = heart.radiomics.notdeprecated[,
                                                      grep("f.eid|MYO|shape",
                                                  colnames(heart.radiomics.notdeprecated))]
```

# Prep Traditional Metrics
```{r}
heart.traditional = heart.traditional[,grepl('cmr_|f.eid',colnames(heart.traditional))]
```

# Prep Bai
```{r}
colnames(heart.bai) = lapply(colnames(heart.bai),function(x) paste('cmr',strsplit(x,'..',fixed=TRUE)[[1]][1],sep='_'))
colnames(heart.bai)[1] = 'f.eid'
```

# Match IDs
```{r}
heart.bai.complete = heart.bai[complete.cases(heart.bai),]
heart.traditional.complete = heart.traditional[complete.cases(heart.traditional),]
```

```{r}
dups = duplicated(heart.traditional.complete[,2:ncol(heart.traditional.complete)])
heart.traditional.unique = heart.traditional.complete[!dups,]
```

```{r}
trunc <- function(x, ..., prec = 0) base::trunc(x * 10^prec, ...) / 10^prec;
```

```{r}
# Create Unique IDs
heart.traditional.unique$new_id = 
  apply(heart.traditional.unique[,c(2,6,7)], 1, function(x) paste(trunc(x, prec=2),collapse=''))
heart.bai.complete$new_id = 
  apply(heart.bai.complete[,c(2,7,8)], 1, function(x) paste(trunc(x, prec=2),collapse=''))
# Test if ID is unique
length(unique(heart.traditional.unique$new_id))/length(heart.traditional.unique$new_id)
length(unique(heart.bai.complete$new_id))/length(heart.bai.complete$new_id)
```

```{r}
heart.merged = merge(heart.traditional.unique, heart.bai.complete, by='new_id')
```

```{r}
heart.merged.bai = heart.merged[,!grepl('new_id|.x|f.eid.y',colnames(heart.merged))]
heart.merged.bai$f.eid = heart.merged$f.eid.x
colnames(heart.merged.bai) = lapply(colnames(heart.merged.bai),function(x) strsplit(x,'.y',fixed=TRUE)[[1]][1])
```


# Merge
```{r}
heart.radiomics.final = heart.radiomics.touse[complete.cases(heart.radiomics.touse),]
heart.imaging.final = merge(heart.merged.bai, heart.radiomics.final,by='f.eid')
heart.imaging.final = heart.imaging.final %>% dplyr::select(f.eid, everything())
```


# Save
```{r}
write.csv(heart.imaging.final,'data_derived/cleaned/heart_cleaned.csv', row.names = FALSE)
```
