---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(finalfit)
library(mice)
library(purrr)
library(dplyr)
```

# Load Data
```{r}
cardio.data = read.csv("data/cardio.data.csv")
brain.confounders = read.csv('data/brain.confounders.csv')
heart.disease.status  = read.csv('data/heart.disease.csv')
brain.disease.status  = read.csv('data/brain.disease.csv')
bsa = read.csv('data/bsa.csv')
extra.cardio.data = read.csv("data/extra.cardio.data.csv")
```

# Process Heart Conditions
```{r}
heart.disease.status$cov_nosevere = apply(heart.disease.status[,2:ncol(heart.disease.status)],1,function(x) !any(x))
heart.disease.status.tomerge = heart.disease.status[,c('f.eid','cov_nosevere')]
```

# Rename Brain Conditions
```{r}
brain.disease.status = dplyr::rename(brain.disease.status, cov_braindisease = neuro_self_report)
```

# Prepare Ethnicity
```{r}
ethnicity.tomerge = extra.cardio.data[,c('f.eid', 'bio.ethnic_background.0.baseline')]
colnames(ethnicity.tomerge) = c('f.eid','cov_ethnicity')
```


# Gather Data
```{r}
cov.data = data.frame("f.eid" = cardio.data$f.eid, 
                      "cov_sex" = cardio.data$cov_sex,
                      "cov_age"= cardio.data$cov_age)
brain.covs = brain.confounders[,grepl('f.eid',colnames(brain.confounders)) | 
                                 grepl('cov',colnames(brain.confounders))]
```

# Merge
```{r}
cov.frames = list(cov.data, brain.covs, heart.disease.status.tomerge, bsa, brain.disease.status, ethnicity.tomerge)
merged.covs = 
  cov.frames %>% 
  purrr::reduce(inner_join,by="f.eid")
merged.covs = merged.covs %>% select(f.eid, everything())
```

# Completeness
```{r}
missing_pattern(merged.covs)
```

```{r}
merged.covs.final = merged.covs[complete.cases(merged.covs),]
merged.covs.final = merged.covs.final %>% select(f.eid, everything())
```


# Save
```{r}
write.csv(merged.covs.final,'data_derived/cleaned/covs_cleaned.csv', row.names = FALSE)
```

