---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(finalfit)
library(mice)
library(purrr)
library(dplyr)
```

# Load Data
```{r}
vrf.latents = read.csv('data_derived/dim_red/latents_vrf.csv')
cog.latents = read.csv('data_derived/dim_red/latents_cog.csv')
heart.latents = read.csv('data_derived/dim_red/latents_heart.csv')
brain.latents = read.csv('data_derived/dim_red/latents_brain.csv')
heart.ccs = read.csv('data_derived/dim_red/latents_heart_ccs.csv')[,1:4]
brain.ccs = read.csv('data_derived/dim_red/latents_brain_ccs.csv')[,1:4]
```

# Flip the Sign of Some Features for Interpretability
```{r}
# Set Heart PC3 to have positive be *more complex*
heart.latents$heart_latent_pc3 = - heart.latents$heart_latent_pc3
# Set Brain PC2 to have positive be *more FA*
brain.latents$brain_latent_pc2 = - brain.latents$brain_latent_pc2
# Flip the CC1 axes so that they increase with greater volume
heart.ccs$heart_latent_cc1 = - heart.ccs$heart_latent_cc1
brain.ccs$brain_latent_cc1 = - brain.ccs$brain_latent_cc1
# Flip the CC2 axes so that they increase with greater ES myocardial intensity / FA 
heart.ccs$heart_latent_cc2 = - heart.ccs$heart_latent_cc2
brain.ccs$brain_latent_cc2 = - brain.ccs$brain_latent_cc2
# Flip the CC3 axes so that they increase with greater ES myocardial intensity / MD
# heart.ccs$heart_latent_cc3 = - heart.ccs$heart_latent_cc3
# brain.ccs$brain_latent_cc3 = - brain.ccs$brain_latent_cc3
```

# Merge
```{r}
all.latents = list(vrf.latents, cog.latents, heart.latents, brain.latents, heart.ccs, brain.ccs)
merged.latents = all.latents %>% 
  purrr::reduce(inner_join,by="f.eid")
merged.latents = merged.latents %>% 
  dplyr::select(f.eid, everything())
```

# Save
```{r}
write.csv(merged.latents,
          'data_derived/merged/latents.csv', row.names = FALSE)
```

