---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(candisc)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
source('functions/explained_variance.R')
source('functions/heatmaps.custom.R')
```

# Load Data
```{r}
merged.data.complete.new = read.csv('data_derived/merged/vrf.cog.heart.brain.new.healthy.csv')
```

```{r}
merged.heart = merged.data.complete.new[,grepl("heart_",colnames(merged.data.complete.new))]
merged.brain = merged.data.complete.new[,grepl("brain_",colnames(merged.data.complete.new))]
```

```{r}
merged.heart.zscore = data.frame(scale(merged.heart))
merged.brain.zscore = data.frame(scale(merged.brain))
```

```{r}
write.csv(merged.brain,'data_derived/dim_red/brain.nozscore.csv',row.names = FALSE)
write.csv(merged.heart,'data_derived/dim_red/heart.nozscore.csv',row.names = FALSE)
```


# CCA Performed in Sklearn
```{r}
brain.ccs = read.csv('data_derived/dim_red/brain_ccs.csv',row.names = 1)
heart.ccs = read.csv('data_derived/dim_red/heart_ccs.csv',row.names = 1)
```

```{r}
cancors = diag(cor(heart.ccs, brain.ccs))
```

```{r}
ggplot() + 
  geom_line(aes(x=seq(1,10),y=cancors)) + 
  theme_classic() + labs(y='Canonical Correlation', x='Covariate Number') + 
  scale_x_continuous(breaks=seq(1,10,1))
ggsave('figures/dim_red/cca.cors.png')
```


```{r}
heart.scores = data.frame(cor(merged.heart.zscore, heart.ccs))
colnames(heart.scores) = paste('Mode',seq(10),sep='')
brain.scores = data.frame(cor(merged.brain.zscore, brain.ccs))
colnames(brain.scores) = paste('Mode',seq(10),sep='')
```

```{r}
write.csv(heart.scores,'tables/dim_red/heart.cca.loadings.csv')
write.csv(brain.scores,'tables/dim_red/brain.cca.loadings.csv')
```

```{r}
pad = data.frame(matrix(NA, nrow=nrow(heart.scores) - nrow(brain.scores), ncol = 10))
colnames(pad) = paste('Mode',seq(10),sep='')
brain.scores.pad = rbind(brain.scores,pad)

heart.brain.scores = cbind(tibble::rownames_to_column(heart.scores)[,1:4],
                           tibble::rownames_to_column(brain.scores.pad)[,1:4])
```

```{r}
write.csv(heart.brain.scores, 'tables/final/heart.brain.cca.scores.csv')
```


```{r}
brain.ccs$f.eid = merged.data.complete.new$f.eid
heart.ccs$f.eid = merged.data.complete.new$f.eid
brain.ccs = brain.ccs %>% dplyr::select(f.eid, everything())
heart.ccs = heart.ccs %>% dplyr::select(f.eid, everything())
```

```{r}
colnames(heart.ccs) = c('f.eid',paste('heart_latent_cc',seq(1,10),sep=''))
colnames(brain.ccs) = c('f.eid',paste('brain_latent_cc',seq(1,10),sep=''))
```


```{r}
write.csv(brain.ccs,'data_derived/dim_red/latents_brain_ccs.csv',row.names = FALSE)
write.csv(heart.ccs,'data_derived/dim_red/latents_heart_ccs.csv',row.names = FALSE)
```

# Heatmap

```{r}
merged.heart.zscore = merged.heart.zscore[,order(colnames(merged.heart.zscore))]
merged.brain.zscore = merged.brain.zscore[,order(colnames(merged.brain.zscore))]

heart.brain.cor = cor(merged.heart.zscore, merged.brain.zscore)
heart.groups = sapply(colnames(merged.heart.zscore),function(x) strsplit(x,'_')[[1]][2])
heart.groups = factor(heart.groups, levels = c("shape","intensity","texture"))
group.numbers <- as.numeric(heart.groups)
side.colors <- brewer.pal(9, "Set1")[group.numbers]

brain.groups = sapply(colnames(merged.brain.zscore),function(x) strsplit(x,'_')[[1]][3])
brain.groups[grepl('volume',colnames(merged.brain.zscore))] = 'volume'
brain.groups[grepl('wmh',colnames(merged.brain.zscore))] = 'wmh'
brain.groups = factor(brain.groups)
group.numbers <- as.numeric(brain.groups)
bottom.colors <- brewer.pal(10, "Set3")[group.numbers]
```

```{r}
heart.scores = heart.scores[order(rownames(heart.scores)),]
brain.scores = brain.scores[order(rownames(brain.scores)),]

data = heart.brain.cor[order(heart.scores$Mode1),order(brain.scores$Mode1)]
test.names1 = heart.groups[order(heart.scores$Mode1)]
test.names2 = brain.groups[order(brain.scores$Mode1)]
test.palette1 = side.colors[order(heart.scores$Mode1)]
test.palette2 = bottom.colors[order(brain.scores$Mode1)]
#png(file = 'figures/dim_red/heart.brain.cor.png',width=1200,height=800)
heatmap.with.twobars(data, test.names1, test.names2, test.palette1, test.palette2)
#dev.off()
```


```{r}
#png(file = 'figures/dim_red/heart.cor.png',width=1200,height=800)
heatmap.with.twobars(heart.brain.cor, #[order(heart.scores$X0), order(brain.scores$X0)],
                     heart.groups,#[order(heart.scores$X0)],
                     brain.groups,#[order(brain.scores$X0)],
                     side.colors, #[order(heart.scores$X0)], 
                     bottom.colors) #[order(brain.scores$X0)])
#dev.off()
```


# EVR

```{r}
brain.evrs = read.csv('data_derived/dim_red/brain.evrs.crossval.csv',row.names=1)
heart.evrs = read.csv('data_derived/dim_red/heart.evrs.crossval.csv',row.names=1)
heart.brain.cors = read.csv('data_derived/dim_red/heart.brain.cors.crossval.csv',row.names=1)
```

```{r}
brain.evrs.mean = apply(brain.evrs, 2, mean)
brain.evrs.se = apply(brain.evrs, 2, function(x) sd(x) / length(x))
ggplot() + 
  geom_line(aes(x=seq(1,10),y=brain.evrs.mean)) + 
  geom_errorbar(aes(x = seq(1,10),
                    ymin=brain.evrs.mean - 2 * brain.evrs.se, 
                    ymax=brain.evrs.mean + 2 * brain.evrs.se), width=.2) + 
  ylim(0,0.2) + 
  theme_classic() + labs(y='Explained Variance Ratio', x='Component Number') + 
  scale_x_continuous(breaks=seq(1,10,1)) 
ggsave('figures/dim_red/brain.cca.evr.cval.png')
```

```{r}
heart.evrs.mean = apply(heart.evrs, 2, mean)
heart.evrs.se = apply(heart.evrs, 2, function(x) sd(x) / length(x))
ggplot() + 
  geom_line(aes(x=seq(1,10),y=heart.evrs.mean)) + 
  geom_errorbar(aes(x = seq(1,10),
                    ymin=heart.evrs.mean - 2 * heart.evrs.se, 
                    ymax=heart.evrs.mean + 2 * heart.evrs.se), width=.2) + 
  ylim(0,0.2) + 
  theme_classic() + labs(y='Explained Variance Ratio', x='Component Number') + 
  scale_x_continuous(breaks=seq(1,10,1)) 
ggsave('figures/dim_red/heart.cca.evr.cval.png')
```

```{r}
cors.mean = apply(heart.brain.cors, 2, mean)
cors.se = apply(heart.brain.cors, 2, function(x) sd(x) / length(x))
ggplot() + 
  geom_line(aes(x=seq(1,10),y=cors.mean)) + 
  geom_errorbar(aes(x = seq(1,10),
                    ymin=cors.mean - 2 * cors.se, 
                    ymax=cors.mean + 2 * cors.se), width=.2) + 
  ylim(0,0.8) + 
  theme_classic() + labs(y='Correlation', x='Component Number') + 
  scale_x_continuous(breaks=seq(1,10,1)) 
ggsave('figures/dim_red/cca.cors.cval.png')
```