---
title: "R Notebook"
output: html_notebook
---


# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(lavaan)
library(semPlot)
library(paran)
library(factoextra)
library(RColorBrewer)
source('functions/explained_variance.R')
source('functions/heatmaps.custom.R')
```

# Load Data
```{r}
vrf.cog.heart.brain.trad = read.csv('data_derived/merged/vrf.cog.heart.brain.trad.healthy.csv')
```

```{r}
merged.heart = vrf.cog.heart.brain.trad[,grep("heart_",colnames(vrf.cog.heart.brain.trad))]
merged.heart.zscore = scale(merged.heart)
```


# PCA
```{r}
heart.pca = prcomp(merged.heart.zscore, center = FALSE, scale = FALSE)
heart.variances = summary(heart.pca)$importance
```

```{r}
#Varimax
ncomp = 3
raw.loadings      = heart.pca$rotation[,1:ncomp] %*% diag(heart.pca$sdev, ncomp, ncomp)
rotated.loadings  = varimax(raw.loadings)$loadings
inv.loadings      = t(pracma::pinv(rotated.loadings))
heart.varimax.scores = scale(merged.heart.zscore) %*% inv.loadings
```

```{r}
write.csv(rotated.loadings ,"tables/dim_red/heart.varimax.loadings.csv")
```


```{r}
#Explained variances before and after Varimax
evr_orth(merged.heart.zscore, heart.pca$x[,1:3])
evr_nonorth(merged.heart.zscore, data.frame(heart.varimax.scores))
```



```{r}
png("figures/dim_red/heart.eigs.png")
fviz_eig(heart.pca,ncp=10) 
dev.off()
```


```{r}
heart.latents = data.frame('f.eid'=vrf.cog.heart.brain.trad$f.eid)
heart.latents$heart_latent_pc1 = heart.varimax.scores[,1]
heart.latents$heart_latent_pc2 = heart.varimax.scores[,2]
heart.latents$heart_latent_pc3 = heart.varimax.scores[,3]
```

```{r}
write.csv(heart.latents, 'data_derived/dim_red/latents_heart.csv',row.names = FALSE)
```

```{r}
write.csv(heart.pca$rotation[,1:3],"tables/dim_red/heart.pca.loadings.csv")
```

```{r}
heart.cor = cor(merged.heart)
heart.groups = sapply(colnames(merged.heart),function(x) strsplit(x,'_')[[1]][2])
heart.groups = factor(heart.groups, levels = c("shape","intensity","texture"))
group.numbers <- as.numeric(heart.groups)
side.colors <- brewer.pal(9, "Set1")[group.numbers]
#png(file = 'figures/dim_red/heart.cor.png',width=1200,height=800)
heatmap.with.tree(heart.cor,heart.groups,side.colors)
#dev.off()
```

```{r}
side.colors
```

```{r}
heart.scaled = scale(merged.heart)
heart.pcs = heart.latents[,grepl('heart',colnames(heart.latents))]
evr(heart.scaled,heart.pcs[,1,drop=F])
```


