---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(lavaan)
library(semPlot)
library(factoextra)
library(RColorBrewer)
source('functions/heatmaps.custom.R')
source('functions/explained_variance.R')
```

# Load Data
```{r}
merged.data.complete = read.csv('data_derived/merged/vrf.cog.heart.brain.trad.healthy.csv')
merged.data.complete.new = read.csv('data_derived/merged/vrf.cog.heart.brain.new.healthy.csv')
tract.names = read.csv('data/tract.names.csv')
```

# Brain Factor Analysis
## gMD 
```{r}
merged.brain.md = merged.data.complete[,grepl("brain_",colnames(merged.data.complete))&
                                        grepl("mean_md",colnames(merged.data.complete))]
merged.brain.md = scale(data.frame(lapply(merged.brain.md,as.numeric)))
ordered_tracts = colnames(merged.brain.md)[order(colnames(merged.brain.md))]
gMD = paste(c("gMD=~",ordered_tracts),collapse="+")
```

```{r}
md.covariances = character(length(ordered_tracts)/2)
for(i in seq(1,length(ordered_tracts)/2)) {
  md.covariances[i] = paste(ordered_tracts[2*i-1],ordered_tracts[2*i],sep="~~")
}
md.covariances = md.covariances[!grepl("forceps",md.covariances)]
tract_grid = expand.grid(ordered_tracts[grep("inferior",ordered_tracts)],ordered_tracts[grep("inferior",ordered_tracts)])
more.covariances = paste(tract_grid[1:8,]$Var1,tract_grid[1:8,]$Var2,sep="~~")[3:6]
md.covariances = paste(c(md.covariances,more.covariances),collapse="\n")
```

```{r}
gMD_cfa_input = paste(c(gMD,md.covariances),collapse="\n")
gMD_cfa = cfa(gMD_cfa_input, merged.brain.md)
```

```{r}
gMD.metrics = fitMeasures(gMD_cfa, c("cfi","tli","rmsea","srmr"))
gMD.metrics = c(gMD.metrics, 'evr'=evr(merged.brain.md, predict(gMD_cfa)))
gMD.metrics.frame = tibble::rownames_to_column(data.frame(gMD.metrics))
colnames(gMD.metrics.frame) = c('rhs','est.std')
```

# Save all SEM Paramters
```{r}
gMD.table = standardizedSolution(gMD_cfa)
write.csv(gMD.table,"tables/dim_red/gMD_cfa.csv")
```

```{r}
gMD.tracts = gMD.table[gMD.table$op == '=~',]
gMD.tracts = gMD.tracts[order(gMD.tracts$rhs),]
gMD.tracts$rhs = tract.names$name
gMD.final = 
  rbind(dplyr::select(gMD.tracts,c('rhs','est.std')),
        gMD.metrics.frame)
```

```{r}
out = hclust(dist(t(scale(merged.brain.md[,order(colnames(merged.brain.md))]))))
```

```{r}
brain.md.cor = cor(merged.brain.md[,order(colnames(merged.brain.md))])
rownames(brain.md.cor) = as.character(tract.names$name)
heatmap.with.nolabels(brain.md.cor[out$order,out$order], min=-1,max=1,'correlation')
ggsave('figures/dim_red/md.cor.png')
```

## gFA 
```{r}
merged.brain.fa = merged.data.complete[,grepl("brain_",colnames(merged.data.complete))&
                                        grepl("mean_fa",colnames(merged.data.complete))]
merged.brain.fa = scale(data.frame(lapply(merged.brain.fa,as.numeric)))
ordered_tracts = colnames(merged.brain.fa)[order(colnames(merged.brain.fa))]
gfa = paste(c("gfa=~",ordered_tracts),collapse="+")
```

```{r}
fa.covariances = character(length(ordered_tracts)/2)

for(i in seq(1,length(ordered_tracts)/2)) {
  fa.covariances[i] = paste(ordered_tracts[2*i-1],ordered_tracts[2*i],sep="~~")
}
tract_grid = expand.grid(ordered_tracts[grep("inferior",ordered_tracts)],ordered_tracts[grep("inferior",ordered_tracts)])
more.covariances = paste(tract_grid[1:8,]$Var1,tract_grid[1:8,]$Var2,sep="~~")[3:6]
fa.covariances = paste(c(fa.covariances,more.covariances),collapse="\n")
```

```{r}
gfa_cfa_input = paste(c(gfa,fa.covariances),collapse="\n")
gfa_cfa = cfa(gfa_cfa_input, merged.brain.fa)
```

```{r}
gFA.metrics = fitMeasures(gfa_cfa, c("cfi","tli","rmsea","srmr"))
gFA.metrics = c(gFA.metrics, 'evr'=evr(merged.brain.fa, predict(gfa_cfa)))
gFA.metrics.frame = tibble::rownames_to_column(data.frame(gFA.metrics))
colnames(gFA.metrics.frame) = c('rhs','est.std')
```

# Save all SEM Paramters
```{r}
gFA.table = standardizedSolution(gfa_cfa)
write.csv(gFA.table,"tables/dim_red/gFA_cfa.csv")
```

```{r}
gFA.tracts = gFA.table[gFA.table$op == '=~',]
gFA.tracts = gFA.tracts[order(gFA.tracts$rhs),]
gFA.tracts$rhs = tract.names$name
gFA.final = 
  rbind(dplyr::select(gFA.tracts,c('rhs','est.std')),
        gFA.metrics.frame)
```

```{r}
gDTI = cbind(gFA.final, gMD.final)
colnames(gDTI) = c('Tract1', 'FA', 'Tract2','MD')
gDTI = gDTI[,colnames(gDTI) != 'Tract2']
write.csv(gDTI,"tables/final/gDTI_cfa.csv")
```



```{r}
brain.fa.cor = cor(merged.brain.fa[,order(colnames(merged.brain.fa))])
rownames(brain.fa.cor) = as.character(tract.names$name)
heatmap.with.nolabels(brain.fa.cor[out$order,out$order], min=-1,max=1,'correlation')
ggsave('figures/dim_red/fa.cor.png')
```



# Brain PCA

```{r}
merged.brain.new = merged.data.complete.new[,grepl("brain_",colnames(merged.data.complete.new))]
```

```{r}
brain.pca = prcomp(merged.brain.new, center = TRUE, scale = TRUE)
brain.variances = summary(brain.pca)$importance
```

# Cross Validation
```{r}
brain.evrs = pca.cross.val(merged.brain.new, 10)
```

```{r}
brain.evrs.mean = apply(brain.evrs, 2, mean)
brain.evrs.se = apply(brain.evrs, 2, function(x) sd(x) / length(x))
ggplot() + 
  geom_line(aes(x=seq(1,10),y=brain.evrs.mean)) + 
  geom_errorbar(aes(x = seq(1,10),
                    ymin=brain.evrs.mean - 2 * brain.evrs.se, 
                    ymax=brain.evrs.mean + 2 * brain.evrs.se), width=.2) + 
  ylim(0,0.32) + 
  theme_classic() + labs(y='Explained Variance Ratio', x='Principal Component') + 
  scale_x_continuous(breaks=seq(1,10,1)) 
ggsave('figures/dim_red/brain.eigs.cval.png')
```



```{r}
png("figures/dim_red/brain.eigs.png")
fviz_eig(brain.pca,ncp=10) 
dev.off()
```

```{r}
write.csv(brain.pca$rotation[,1:10],"tables/dim_red/brain.pca.loadings.csv")
write.csv(brain.pca$rotation[,1:3],"tables/final/brain.pca.loadings.csv")
```

```{r}
brain.cor = cor(merged.brain.new)
brain.groups = sapply(colnames(merged.brain.new),function(x) strsplit(x,'_')[[1]][3])
brain.groups[grepl('volume',colnames(merged.brain.new))] = 'volume'
brain.groups[grepl('wmh', colnames(merged.brain.new))] = 'volume'
brain.groups = factor(brain.groups)
group.numbers <- as.numeric(brain.groups)
side.colors <- brewer.pal(10, "Set3")[group.numbers]
png(file = 'figures/dim_red/brain.cor.png',width=1200,height=1000)
heatmap.with.tree(brain.cor,brain.groups,side.colors)
```


# Save Latents

```{r}
brain.latents = data.frame('f.eid'=merged.data.complete$f.eid)
brain.latents$brain_latent_grey = merged.data.complete$brain_grey
brain.latents$brain_latent_atrophy = merged.data.complete$brain_atrophy
brain.latents$brain_latent_wmh = merged.data.complete$brain_wmh
brain.latents$brain_latent_gMD = predict(gMD_cfa)
brain.latents$brain_latent_gFA = predict(gfa_cfa)
brain.latents$brain_latent_pc1 = brain.pca$x[,1]
brain.latents$brain_latent_pc2 = brain.pca$x[,2]
brain.latents$brain_latent_pc3 = brain.pca$x[,3]
```

```{r}
write.csv(brain.latents, 'data_derived/dim_red/latents_brain.csv',row.names = FALSE)
```


