---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(lavaan)
library(semPlot)
library(factoextra)
source('functions/explained_variance.R')
source('functions/heatmaps.custom.R')
```

# Load Data
```{r}
vrf.cog.heart.brain.trad = read.csv('data_derived/merged/vrf.cog.heart.brain.trad.healthy.csv')
```

```{r}
cog.merged = vrf.cog.heart.brain.trad[,grep("cog_",colnames(vrf.cog.heart.brain.trad))]
```


# CFA for g
```{r}
cog.merged = data.frame(lapply(cog.merged,as.numeric))
g = paste(c("g=~",colnames(cog.merged)),collapse="+")
g_cfa = cfa(g, cog.merged)
```

```{r}
g.metrics = fitMeasures(g_cfa, c("cfi","tli","rmsea","srmr"))
g.metrics.frame = tibble::rownames_to_column(data.frame(g.metrics))
colnames(g.metrics.frame) = c('rhs','est.std')
```

# Save all SEM Paramters
```{r}
g.table = standardizedSolution(g_cfa)
write.csv(g.table,"tables/dim_red/g_cfa.csv")
```


```{r}
g.final = 
  rbind(dplyr::select(g.table[g.table$op == '=~',],c('rhs','est.std')),
        g.metrics.frame)
write.csv(g.final,"tables/final/g.cfa.csv")
```

# Path Diagram

```{r}
labels = c("vnr", "vismem", "rt","promem","g")
semPaths(g_cfa,what="std",fade=FALSE,nodeLabels=labels,edge.label.cex=1,sizeMan=5,edge.color="black",
         curve=2,mar=c(10,5,5,5),
         filetype='png',filename="figures/dim_red/g")
```

```{r}
cog.cor = cor(cog.merged)
colnames(cog.cor) = sapply(colnames(cog.cor),function(x) strsplit(x,'_')[[1]][2])
heatmap.with.labels(cog.cor,-1,1,'correlation')
ggsave('figures/dim_red/cog.cor.png')
```

```{r}
cog.aggregate = data.frame('f.eid' = vrf.cog.heart.brain.trad$f.eid)
cog.aggregate$cog_latent_g = predict(g_cfa)
```


```{r}
write.csv(cog.aggregate,'data_derived/dim_red/latents_cog.csv',row.names = FALSE)
```

