---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(finalfit)
library(mice)
library(purrr)
library(dplyr)
library(lavaan)
library(ggplot2)
library(gplots)
```

# Load Data
```{r}
latents.covariates.scaled = 
  read.csv('data_derived/merged/latents.covariates.scaled.csv')
latents.covariates.residualized.scaled = read.csv('data_derived/merged/latents.covariates.residualized.scaled.csv')
all.features = 
  read.csv('data_derived/merged/vrf.cog.heart.brain.new.healthy.csv')
```

# Individual Brain Feature Mediation 

## Scale and Residualize Brain Features

```{r}
brain = all.features[,grepl('brain_',colnames(all.features))]
```

```{r}
brain.residualized = brain
brain.model = brain
brain.model$cov_headsize = all.features$cov_headsize
brain.model$cov_pos_x = all.features$cov_pos_x
brain.model$cov_pos_y = all.features$cov_pos_y
brain.model$cov_pos_z = all.features$cov_pos_z
for(latent in colnames(brain)) {
  lin.model = paste(c(latent," ~ -cov_headsize + cov_pos_x + cov_pos_y + cov_pos_z"),collapse='')
  brain.residualized[,latent] = rstandard(lm(lin.model, brain.model))
}
brain = data.frame(scale(brain))
```

```{r}
latents.covariates.brain = cbind(latents.covariates.scaled, brain)
latents.covariates.brain.residualized = cbind(latents.covariates.residualized.scaled, brain.residualized)
```

# Individual Brain Feature Mediation 
```{r}
effects = 
"de := c
ie := a*b
te := c + a*b"

ind.results.brain = list()
for(mediator in colnames(brain)) {
  med.model = paste(c(mediator," ~ a * cardio_latent_gvrf + cov_age + cov_sex\n",
                      "cog_latent_g ~ c*cardio_latent_gvrf + b *",mediator,"+cov_age + cov_sex"),
                    collapse = "")
  med.model = paste(c(med.model, effects), collapse = '\n')
  med.sem = 
    sem(med.model,latents.covariates.brain)
  out = standardizedsolution(med.sem)
  ind.results.brain[[mediator]] = out[out$op=="~"|out$op==":=",]
}
```

```{r}
brain.ind.frame = bind_rows(ind.results.brain, .id = "mediator")
```

```{r}
get.nickname = function(name) {
  if(grepl('volume',name)) {
    return('volume')
  } else {
    return(strsplit(name,'_')[[1]][3])
  }
}
```

```{r}
brain.des = brain.ind.frame[brain.ind.frame$lhs == 'de',]
brain.des$pvalue_adj = p.adjust(brain.des$pvalue,'BH')
brain.des$feature = sapply(brain.des$mediator, get.nickname)
```

```{r}
brain.des$sig = brain.des$pvalue_adj < 0.05
ggplot(brain.des, aes(x = feature, y = est.std, fill = feature)) + 
  geom_boxplot() + 
  geom_point(position = position_jitter(0.1)) + 
  ylab("direct effect") + 
  scale_alpha_discrete('significant',labels=c('True','False')) + 
  scale_y_continuous(breaks=seq(-0.05,0.05,0.05),limits=c(-0.075,0.075)) +
  theme_classic()+ 
    theme(
  axis.title.x = element_blank(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank())
ggsave('figures/analysis/direct.individual.single.brain.png')
```
```{r}
write.csv(brain.des,"tables/analysis/direct.individual.single.brain.csv")
```


## Individual Brain Mediation Indirect
```{r}
brain.ies = brain.ind.frame[brain.ind.frame$lhs == 'ie',]
brain.ies$pvalue_adj = p.adjust(brain.ies$pvalue,'BH')
brain.ies$feature = sapply(brain.ies$mediator, get.nickname)
```

```{r}
brain.ies$sig = (brain.ies$pvalue_adj < 0.05) & (!is.na(brain.ies$pvalue_adj))
ggplot(brain.ies, aes(x = feature, y = est.std, fill = feature)) + 
  geom_boxplot() + 
  geom_point(aes(alpha=sig), position = position_jitter(0.1)) + 
  ylab("indirect effect") + 
  scale_alpha_discrete('significant',labels=c('False','True')) + 
  scale_y_continuous(breaks=seq(-0.01,0.01,0.01),limits=c(-0.015,0.015)) +
  theme_classic()+ 
    theme(
  axis.title.x = element_blank(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank())
ggsave('figures/analysis/indirect.individual.single.brain.png')
```

```{r}
write.csv(brain.ies,"tables/analysis/indirect.individual.single.brain.csv")
```

```{r}
write.csv(brain.ind.frame,"tables/analysis/mediation.individual.single.brain.csv")
```


# Individual Brain Feature Mediation Residualized
```{r}
ind.results.brain.resid = list()
for(mediator in colnames(brain)) {
  med.model = paste(c(mediator," ~ a * cardio_latent_gvrf + cov_age + cov_sex\n",
                      "cog_latent_g ~ c*cardio_latent_gvrf + b *",mediator,"+cov_age + cov_sex"),
                    collapse = "")
  med.model = paste(c(med.model, effects), collapse = '\n')
  med.sem = 
    sem(med.model,latents.covariates.brain.residualized)
  out = standardizedsolution(med.sem)
  ind.results.brain.resid[[mediator]] = out[out$op=="~"|out$op==":=",]
}
```

```{r}
brain.ind.frame.resid = bind_rows(ind.results.brain.resid, .id = "mediator")
```

```{r}
brain.des.resid = brain.ind.frame.resid[brain.ind.frame.resid$lhs == 'de',]
brain.des.resid$pvalue_adj = p.adjust(brain.des.resid$pvalue,'BH')
brain.des.resid$feature = sapply(brain.ies$mediator, get.nickname)
```

```{r}
brain.des.resid$sig = brain.des.resid$pvalue_adj < 0.05
ggplot(brain.des.resid, aes(x = nickname, y = est.std, fill = feature)) + 
  geom_boxplot() + 
  geom_point( position = position_jitter(0.1)) + 
  ylab("direct effect") + 
  scale_alpha_discrete('significant',labels=c('False','True')) + 
  scale_y_continuous(breaks=seq(-0.05,0.05,0.05),limits=c(-0.075,0.075)) +
  theme_classic()+ 
    theme(
  axis.title.x = element_blank(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank())
ggsave('figures/analysis/direct.individual.single.brain.residualized.png')
```

```{r}
write.csv(brain.des,"tables/analysis/direct.individual.single.brain.residualized.csv")
```


## Individual Brain Mediation Indirect
```{r}
brain.ies.resid = brain.ind.frame.resid[brain.ind.frame.resid$lhs == 'ie',]
brain.ies.resid$pvalue_adj = p.adjust(brain.ies.resid$pvalue,'BH')
brain.ies.resid$feature = sapply(brain.ies.resid$mediator, get.nickname)
```

```{r}
brain.ies.resid$sig = (brain.ies.resid$pvalue_adj < 0.05) & (!is.na(brain.ies.resid$pvalue_adj))
ggplot(brain.ies.resid, aes(x = feature, y = est.std, fill = feature)) + 
  geom_boxplot() + 
  geom_point(aes(alpha=sig), position = position_jitter(0.1)) + 
  ylab("indirect effect") + 
  scale_alpha_discrete('significant',labels=c('False','True')) + 
  scale_y_continuous(breaks=seq(-0.01,0.01,0.01),limits=c(-0.015,0.015)) +
  theme_classic()+ 
    theme(
  axis.title.x = element_blank(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank())
ggsave('figures/analysis/indirect.individual.single.brain.residualized.png')
```

```{r}
write.csv(brain.ies,"tables/analysis/indirect.individual.single.brain.residualized.csv")
```

```{r}
write.csv(brain.ind.frame.resid,"tables/analysis/mediation.individual.single.brain.residualized.csv")
```

