---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(finalfit)
library(mice)
library(purrr)
library(dplyr)
library(lavaan)
library(ggplot2)
library(gplots)
```

# Load Data
```{r}
latents.covariates.scaled = 
  read.csv('data_derived/merged/latents.covariates.scaled.csv')
latents.covariates.residualized.scaled = read.csv('data_derived/merged/latents.covariates.residualized.scaled.csv')
```

# Simple Mediation Model for each Mediator 
```{r}
effects = 
"de := c
ie := a*b
te := c + a*b"
```

```{r}
mediators = colnames(latents.covariates.scaled)[grepl('latent',colnames(latents.covariates.scaled)) &
                                                grepl('heart|brain',colnames(latents.covariates.scaled))]
med.results = list()
for(mediator in mediators) {
  med.model = paste(c(mediator," ~ a * cardio_latent_gvrf + cov_age + cov_sex\n",
                      "cog_latent_g ~ c*cardio_latent_gvrf + b *",mediator,"+cov_age + cov_sex"),
                    collapse = "")
  med.model = paste(c(med.model, effects), collapse = '\n')
  med.sem = 
    sem(med.model,latents.covariates.scaled)
  out = standardizedsolution(med.sem)
  med.results[[mediator]] = out[out$op=="~"|out$op==":=",]
}
```

```{r}
med.frame = bind_rows(med.results, .id = "mediator")
med.frame$pvalue_adj = med.frame$pvalue 
med.frame$pvalue_adj[med.frame$lhs=='de'] = p.adjust(med.frame$pvalue[med.frame$lhs=='de'],'BH')
med.frame$pvalue_adj[med.frame$lhs=='ie'] = p.adjust(med.frame$pvalue[med.frame$lhs=='ie'],'BH')
write.csv(med.frame,"tables/analysis/mediation.latents.single.csv")
```

```{r}
des = med.frame[med.frame$lhs=='de',]
ies = med.frame[med.frame$lhs=='ie',]
```

```{r}
ggplot(des, aes(x=mediator, y=est.std)) + 
  geom_bar(stat="identity", fill='darkred') + 
  geom_errorbar(aes(ymin=ci.lower, ymax=ci.upper),width=.2) + 
  ylab('direct effect') + 
  theme_classic() +  scale_y_continuous(breaks=seq(-0.1,0.1,0.05),limits=c(-0.12,0.12)) +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.9, hjust=1))
ggsave('figures/analysis/direct.latents.single.png')
```

```{r}
ggplot(ies, aes(x=mediator, y=est.std)) + 
  geom_bar(stat="identity", fill ='darkblue') + 
  geom_errorbar(aes(ymin=ci.lower, ymax=ci.upper),width=.2) + 
  ylab('indirect effect') + 
  theme_classic() + scale_y_continuous(breaks=seq(-0.05,0.05,0.05),limits=c(-0.1,0.1)) +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.9, hjust=1))
ggsave('figures/analysis/indirect.latents.single.png')
```

# Simple Mediation Model for each Mediator Residualized

```{r}
med.results.resid = list()
for(mediator in mediators) {
  med.model = paste(c(mediator," ~ a * cardio_latent_gvrf + cov_age + cov_sex\n",
                      "cog_latent_g ~ c*cardio_latent_gvrf + b *",mediator,"+cov_age + cov_sex"),
                    collapse = "")
  med.model = paste(c(med.model, effects), collapse = '\n')
  med.sem = 
    sem(med.model,latents.covariates.residualized.scaled)
  out = standardizedsolution(med.sem)
  med.results.resid[[mediator]] = out[out$op=="~"|out$op==":=",]
}
```

```{r}
med.frame.resid = bind_rows(med.results.resid, .id = "mediator")
med.frame.resid$pvalue_adj = med.frame.resid$pvalue 
med.frame.resid$pvalue_adj[med.frame.resid$lhs=='de'] = p.adjust(med.frame.resid$pvalue[med.frame.resid$lhs=='de'],'BH')
med.frame.resid$pvalue_adj[med.frame.resid$lhs=='ie'] = p.adjust(med.frame.resid$pvalue[med.frame.resid$lhs=='ie'],'BH')
write.csv(med.frame.resid,"tables/analysis/mediation.latents.single.residualized.csv")
```

```{r}
des.resid = med.frame.resid[med.frame.resid$lhs=='de',]
ies.resid = med.frame.resid[med.frame.resid$lhs=='ie',]
```

```{r}
ggplot(des.resid, aes(x=mediator, y=est.std)) + 
  geom_bar(stat="identity", fill='darkred') + 
  geom_errorbar(aes(ymin=ci.lower, ymax=ci.upper),width=.2) + 
  ylab('direct effect') + 
  theme_classic() +  scale_y_continuous(breaks=seq(-0.1,0.1,0.05),limits=c(-0.12,0.12)) +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.9, hjust=1))
ggsave('figures/analysis/direct.latents.single.residualized.png')
```

```{r}
ggplot(ies.resid, aes(x=mediator, y=est.std)) + 
  geom_bar(stat="identity", fill ='darkblue') + 
  geom_errorbar(aes(ymin=ci.lower, ymax=ci.upper),width=.2) + 
  ylab('indirect effect') + 
  theme_classic() + scale_y_continuous(breaks=seq(-0.05,0.05,0.05),limits=c(-0.1,0.1)) +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.9, hjust=1))
ggsave('figures/analysis/indirect.latents.single.residualized.png')
```