---
title: "R Notebook"
output: html_notebook
---

# Set Up
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
```

# Imports
```{r}
library(finalfit)
library(mice)
library(purrr)
library(dplyr)
library(lavaan)
library(ggplot2)
library(gplots)
source('functions/heatmaps.custom.R')
```

# Load Data
```{r}
latents.covariates.scaled = 
  read.csv('data_derived/merged/latents.covariates.scaled.csv')
latents.covariates.residualized.scaled = read.csv('data_derived/merged/latents.covariates.residualized.scaled.csv')
```

# Linear Model Each Variable against other variable + covariates 

```{r}
latent.names = colnames(latents.covariates.scaled)[grepl('latent',colnames(latents.covariates.scaled))]
```

```{r}
lin.model = paste(c(latent.names[1]," ~ ", latent.names[2], "+ cov_age + cov_sex\n"),collapse = "")
lin.model.sem = sem(lin.model,latents.covariates.scaled)
out = standardizedsolution(lin.model.sem)
dummy = out[out$op=="~"|out$op==":=",]
dummy$est.std = rep(0,3)
```

```{r}
lin.model.pairwise = list()
for(my.var in latent.names) {
  lin.model.pairwise[[my.var]] = list()
  baseline = paste(c(my.var," ~ cov_age + cov_sex\n"),collapse = "")
  baseline.sem = sem(baseline,latents.covariates.scaled)
  baseline.r = lavInspect(baseline.sem,'rsquare')
  for(my.other.var in latent.names) {
    # Fill with blanks if matched with self
    if (my.var == my.other.var) {
      dummy$lhs = rep(my.var,3)
      dummy$rhs[1] = my.other.var
      lin.model.pairwise[[my.var]][[my.other.var]] = dummy
      next
    }
    lin.model = paste(c(my.var," ~ ", my.other.var, "+ cov_age + cov_sex\n"),collapse = "")
    lin.model.sem = sem(lin.model,latents.covariates.scaled)
    out = standardizedsolution(lin.model.sem)
    out$model.r = c(lavInspect(lin.model.sem,'rsquare'),rep(NA,9))
    out$additional.r = c(lavInspect(lin.model.sem,'rsquare') - baseline.r,rep(NA,9))
    lin.model.pairwise[[my.var]][[my.other.var]] = out[out$op=="~"|out$op==":=",]
  }
}
```

```{r}
coef.grid = array(dim=c(length(latent.names), length(latent.names)), 
                  dimnames = list(latent.names, latent.names))
i = 1
for(my.var in latent.names) {
  j = 1
  for(my.other.var in latent.names) {
    coef.grid[i,j] = lin.model.pairwise[[my.var]][[my.other.var]]$est.std[1]
    j = j + 1
  }
  i = i + 1
}
```


```{r}
heatmap.with.labels(coef.grid, -1,1,'coefficient')
ggsave('figures/analysis/linear.pairwise.png')
```


```{r}
lin.to.save = bind_rows(unlist(lin.model.pairwise,recursive=FALSE))
lin.to.save$pvalue_adj = lin.to.save$pvalue 
lin.to.save$pvalue_adj[!grepl('cov_',lin.to.save$rhs)] = p.adjust(lin.to.save$pvalue_adj[!grepl('cov_',lin.to.save$rhs)],'BH')
write.csv(lin.to.save[
  lin.to.save $rhs %in% latent.names,],
  "tables/analysis/linear.model.pairwise.csv")
```

```{r}
lin.to.save.final = dplyr::select(lin.to.save, -c('op','z','se'))
lin.to.save.final = lin.to.save.final[(lin.to.save$rhs %in% latent.names) & (lin.to.save$rhs != lin.to.save$lhs),]
write.csv(lin.to.save.final,
          "tables/final/linear.model.pairwise.csv")
```

# Linear Model Each Variable against other variable + covariates, Residualized

```{r}
latent.names = colnames(latents.covariates.scaled)[grepl('latent',colnames(latents.covariates.scaled))]
```

```{r}
lin.model.pairwise.residualized = list()
for(my.var in latent.names) {
  lin.model.pairwise.residualized[[my.var]] = list()
  baseline = paste(c(my.var," ~ cov_age + cov_sex + cov_age*cov_sex\n"),collapse = "")
  baseline.sem = sem(baseline,latents.covariates.residualized.scaled)
  baseline.r = lavInspect(baseline.sem,'rsquare')
  for(my.other.var in latent.names) {
    # Fill with blanks if matched with self
    if (my.var == my.other.var) {
      dummy$lhs = rep(my.var,3)
      dummy$rhs[1] = my.other.var
      lin.model.pairwise.residualized[[my.var]][[my.other.var]] = dummy
      next
    }
    lin.model = paste(c(my.var," ~ ", my.other.var, "+ cov_age + cov_sex + cov_age:cov_sex\n"),collapse = "")
    lin.model.sem = sem(lin.model,latents.covariates.residualized.scaled)
    out = standardizedsolution(lin.model.sem)
    out$model.r = c(lavInspect(lin.model.sem,'rsquare'),rep(NA,14))
    out$additional.r = c(lavInspect(lin.model.sem,'rsquare') - baseline.r,rep(NA,14))
    lin.model.pairwise.residualized[[my.var]][[my.other.var]] = out[out$op=="~"|out$op==":=",]
  }
}
```



```{r}
coef.grid.resid = array(dim=c(length(latent.names), length(latent.names)), 
                  dimnames = list(latent.names, latent.names))
i = 1
for(my.var in latent.names) {
  j = 1
  for(my.other.var in latent.names) {
    if (j == i) {
      coef.grid.resid[i,j] = NA
    } else {
      coef.grid.resid[i,j] = lin.model.pairwise.residualized[[my.var]][[my.other.var]]$est.std[1]
    }
    
    j = j + 1
  }
  i = i + 1
}
```

```{r}
heatmap.with.labels(coef.grid.resid, -1,1,'coefficient')
ggsave('figures/analysis/linear.pairwise.residualized.png')
```


```{r}
lin.to.save.residualized = bind_rows(unlist(lin.model.pairwise.residualized,recursive=FALSE))
lin.to.save.residualized$pvalue_adj = lin.to.save.residualized$pvalue 
lin.to.save.residualized$pvalue_adj[!grepl('cov_',lin.to.save.residualized$rhs)] = p.adjust(lin.to.save.residualized$pvalue_adj[!grepl('cov_',lin.to.save.residualized$rhs)],'BH')
write.csv(lin.to.save.residualized[
  lin.to.save.residualized $rhs %in% latent.names,],
  "tables/analysis/linear.model.pairwise.residualized.csv")
```

```{r}
lin.to.save.residualized.final = dplyr::select(lin.to.save.residualized, -c('z','se'))
lin.to.save.residualized.final = lin.to.save.residualized.final[
  (lin.to.save.residualized$rhs %in% latent.names) & (lin.to.save.residualized$rhs != lin.to.save.residualized$lhs),]
write.csv(lin.to.save.residualized.final,
          "tables/final/linear.model.pairwise.residualized.csv")
```

```{r}
gvrf.associations.final = lin.to.save.residualized.final[grepl('gvrf',lin.to.save.residualized.final$lhs),]
write.csv(gvrf.associations.final,
          "tables/final/gvrf.associations.csv")
```

```{r}
g.associations.final = lin.to.save.residualized.final[grepl('cog_latent_g',lin.to.save.residualized.final$lhs),]
write.csv(g.associations.final,
          "tables/final/g.associations.csv")
```

```{r}
gvrf.heart.brain = lin.to.save.residualized[grepl('gvrf',lin.to.save.residualized$lhs) & 
                                              grepl('heart|brain',lin.to.save.residualized$rhs),]
test = factor(grepl('heart',gvrf.heart.brain$rhs))
levels(test) = c('brain','heart')
gvrf.heart.brain$class = test
gvrf.heart.brain$sig = (gvrf.heart.brain$pvalue_adj < 0.05) & (!is.na(gvrf.heart.brain$pvalue_adj))
```

```{r}
ggplot(gvrf.heart.brain, aes(x = class, y = additional.r, fill = class)) + 
  geom_boxplot(outlier.shape = NA) + 
  geom_point(position = position_jitter(0.1)) + 
  ylab("Additional R-squared") + 
  #scale_alpha_discrete('significant',labels=c('False','True')) + 
  ylim(0,0.2) +
  ggtitle('gVRF') + 
  theme_classic()+ 
    theme(
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  plot.title = element_text(face='bold',hjust = 0.5)) +
  scale_fill_manual(values = paletteer::paletteer_c("grDevices::Blue-Red",6)[c(2,5)] )
ggsave('figures/analysis/linear.gvrf.residualized.png')
```

```{r}
g.heart.brain = lin.to.save.residualized[grepl('cog_latent_g',lin.to.save.residualized$lhs) & 
                                              grepl('heart|brain',lin.to.save.residualized$rhs),]
test = factor(grepl('heart',g.heart.brain$rhs))
levels(test) = c('brain','heart')
g.heart.brain$class = test
g.heart.brain$sig = (g.heart.brain$pvalue_adj < 0.05) & (!is.na(g.heart.brain$pvalue_adj))
```

```{r}
ggplot(g.heart.brain, aes(x = class, y = additional.r, fill=class)) + 
  geom_boxplot(outlier.shape = NA) + 
  geom_point(aes(alpha=sig), position = position_jitter(0.1)) + 
  ylab("Additional R-squared") + 
  scale_alpha_discrete('significant',labels=c('False','True')) +
  ggtitle('g') + 
  scale_y_continuous(breaks=seq(0,0.05,0.02),limits=c(0,0.05)) +
  theme_classic()+ 
    theme(
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  plot.title = element_text(face='bold',hjust = 0.5)) + 
  scale_fill_manual(values = paletteer::paletteer_c("grDevices::Blue-Red",6)[c(2,5)] )
ggsave('figures/analysis/linear.g.residualized.png')
```



